#include<stdio.h>
#include<conio.h>
#include<stdlib.h> // Header file for standard library of c
#include<time.h>  // time header file

int main()
{
    int i;  // variable declaration to maintane the for loop
    time_t t;

    // time_t is a datatype defined for storing system time values.
    // Such values are returned from the standard " time() " library function


    printf("Random Number Generated by rand() funtion\n");

    // Initializes random number Generator with unique seed value ;
    srand((signed) time(&t));
    // srand(1);

    // Print 10 random number generated  in range [0-15]
    //by rand funtion

  int n = 6;
  while(n--) // Iterating loop 10 times ;
  {
    for(i=0; i<5; i++)
      printf("%d ",((rand() % 16)+4));// range [4-19];

    printf("\n\a");
    getch();
  }

    getch();


    return 0;
}

/* Note
  rand() srand();
  rand() Method is used to generate a series of random numbers
  HEADER file:- cstdlib;

  0. srand() set the starting point of generation of randam number;
  1.The srand() function sets the starting point for producing a series of pseudo-random integers
  2.The pseudo-random number generator should only be seeded once
   before any calls to rand(), or at the start of the program
  3. No need to seed srand() function repeatedly in the program.

  For fixed seed value of srand() function will generated fixed sequence of
  random number on run of program ;

  Note: If random numbers are generated with rand() without first calling srand(),
  your program will create the same sequence of numbers each time it runs.

*/


